#!/usr/bin/env python3
"""GIMP API — REST API server for the GIMP CLI harness.

Auto-generated by api-anything. Wraps the existing Click CLI into
a FastAPI application with multi-tenant session management.

Start the server:
    python -m cli_anything.gimp.gimp_api
    # or after pip install:
    api-anything-gimp --port 8000

Then use the API:
    # Create a session
    curl -X POST http://localhost:8000/sessions

    # Create a project
    curl -X POST http://localhost:8000/project/new \
        -H "X-Session-Id: <session_id>" \
        -H "Content-Type: application/json" \
        -d '{"width": 1920, "height": 1080, "name": "my_image"}'

    # List layers
    curl -H "X-Session-Id: <session_id>" http://localhost:8000/layer/list

    # Interactive docs
    open http://localhost:8000/docs
"""

import sys
import os

# Ensure parent paths are available
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from cli_anything.gimp.gimp_cli import cli
from cli_anything.gimp.core.session import Session
from cli_anything.gimp.utils.api_skin import ApiSkin


def create_app():
    """Create the FastAPI app (for use with uvicorn cli_anything.gimp.gimp_api:create_app)."""
    api = ApiSkin.from_click(
        software="gimp",
        cli_group=cli,
        session_factory=Session,
        version="1.0.0",
    )
    return api.app


def main():
    """CLI entry point for api-anything-gimp."""
    ApiSkin.cli_main(
        software="gimp",
        cli_group=cli,
        session_class=Session,
        version="1.0.0",
    )


if __name__ == "__main__":
    main()
